trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest' # Replace Default with the name of your agent pool if you used a different pool

variables:
  buildConfiguration: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '8.x'
  nodejsVersion: '16.x'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK $(dotnetSdkVersion)'
  inputs:
    packageType: sdk
    version: '$(dotnetSdkVersion)'

- task: NodeTool@0
  displayName: 'Use Node.js $(nodejsVersion)'
  inputs:
    versionSpec: '$(nodejsVersion)' # Especifica a versão do Node.js compatível com node-sass 7.x

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

- script: './node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'
  displayName: 'Compile Sass assets'

- task: gulp@1
  displayName: 'Run gulp tasks'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
  workingDirectory: $(wwwrootDir)

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- template: templates/build.yml
  parameters:
    buildConfiguration: 'debug' # Use 'debug' for development builds, 'release' for production builds

- template: templates/build.yml
  parameters:
    buildConfiguration: 'release' # Use 'release' for production builds 
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  condition: succeeded()

